name: CI

on:
  push:
    branches:
      - master
      - 'features/**'
      - update_master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on ${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chrome, edge ]

    env:
      BROWSER: ${{ matrix.browser }}

    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build and test
        run: mvn clean install

      - name: Install jq for report
        run: sudo apt-get install jq

      - name: Add Cucumber Test Summary
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/output/cucumber.json"
