name: CI

on:
  push:
    branches:
      - main
      - 'features/**'
      - update_master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on ${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chrome, edge ]

    env:
      BROWSER: ${{ matrix.browser }}

    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build and test
        run: mvn clean install

      - name: Publish Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/cucumber-reports